import uuid
from datetime import datetime
from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.database.models import Alert

class AlertsService:
    """
    Alerts Service.
    Persists and queries security alerts generated by high-risk calls.
    """
    async def create_alert(
        self,
        db: AsyncSession,
        analysis_id: str,
        call_id: str,
        alert_level: str,
        title: str,
        message: str,
        reasons: list
    ) -> Alert:
        alert = Alert(
            id=str(uuid.uuid4()),
            analysis_id=analysis_id,
            call_id=call_id,
            alert_level=alert_level,
            title=title,
            message=message,
            reasons=reasons,
            status="ACTIVE",
            created_at=datetime.utcnow()
        )
        db.add(alert)
        await db.commit()
        await db.refresh(alert)
        return alert

    async def get_active_alerts(self, db: AsyncSession, limit: int = 50) -> list:
        result = await db.execute(
            select(Alert).order_by(Alert.created_at.desc()).limit(limit)
        )
        return result.scalars().all()

alerts_service = AlertsService()
